version: '0.1'

services:
  cups:
    container_name: cups
    image: live4ever/cups-avahi-airprint
    #build: .
    restart: always
    network_mode: "host"
    environment:
      CUPSADMIN: cups
      CUPSPASSWORD: cups
    volumes:
      - "./services:/services"
      - "./config:/config"
